Complete Issue/#8 setup repository
FreakyF/Weather-track pull request #17
Opened 2023-07-09 18:02 UTC by FreakyF

2023-07-09 18:48 UTC, Tymisko requested changes

2023-07-09 18:48 UTC, Tymisko commented on README.md
> +From selecting a specific city or location to accessing up-to-the-minute weather updates, every aspect of the user
Do we plan to support `location`?

2023-07-09 19:01 UTC, FreakyF commented on README.md
> +From selecting a specific city or location to accessing up-to-the-minute weather updates, every aspect of the user
I am not entirely certain. I would keep it.

2023-07-09 19:19 UTC, Tymisko commented on README.md
> +From selecting a specific city or location to accessing up-to-the-minute weather updates, every aspect of the user
@FreakyF Create an issue for this functionality.

2023-07-10 10:39 UTC, FreakyF commented on README.md
> +From selecting a specific city or location to accessing up-to-the-minute weather updates, every aspect of the user
@Tymisko i thought about this feature, and we won't support it.

2023-07-10 15:29 UTC, merged