Issue/#19 integrate logging framework
FreakyF/Weather-track pull request #25
Opened 2023-07-12 15:16 UTC by FreakyF

Closes #19

2023-07-12 15:36 UTC, Tymisko requested changes

2023-07-12 15:36 UTC, Tymisko commented on src/main/java/org/weathertrack/Main.java
> +		}
Please remove this code.

2023-07-12 15:36 UTC, Tymisko commented on src/main/resources/logback.xml
Please remove redundant comments

2023-07-12 15:36 UTC, Tymisko commented on src/main/resources/logback.xml
Please add a filter for the console and file to log at different levels. 
Files won't need as many logs as the console need.

2023-07-13 18:54 UTC, Tymisko requested changes

2023-07-13 18:54 UTC, Tymisko commented on src/main/resources/logback.xml
Set minimum logging level for the file to **WARN** and for the console to **INFO**.

2023-07-13 18:54 UTC, Tymisko commented on src/main/resources/logback.xml
Apologize for the previous misunderstanding.

2023-07-13 19:37 UTC, Tymisko requested changes
Please create generic `Logger<T>` interface with following methods:
```java
    void info(String message);
    void warn(String message);
    void error(String message);
    void info(String message, Throwable t);
    void warn(String message, Throwable t);
    void error(String message, Throwable t);
    void info(String format, Object... args);
    void warn(String format, Object... args);
    void error(String format, Object... args);
``` 
create also abstract class `AbstractLogger<T>` which will implement these interface methods as abstract and will have a protected final field with the name of the type specified.
It should also have a protected method `protected String format message (String message)` that will join the class name and message to log. 

And create an implementation for your specific chosen logging framework.
Its implementation name should explicitly describe which framework you are using.

It also should be derived class of `AbstractLogger<T>`.

2023-07-14 11:37 UTC, FreakyF commented
> Please create generic `Logger<T>` interface with following methods:
> 
> ```java
>     void info(String message);
>     void warn(String message);
>     void error(String message);
>     void info(String message, Throwable t);
>     void warn(String message, Throwable t);
>     void error(String message, Throwable t);
>     void info(String format, Object... args);
>     void warn(String format, Object... args);
>     void error(String format, Object... args);
> ```
> 
> create also abstract class `AbstractLogger<T>` which will implement these interface methods as abstract and will have a protected final field with the name of the type specified. It should also have a protected method `protected String format message (String message)` that will join the class name and message to log.
> 
> And create an implementation for your specific chosen logging framework. Its implementation name should explicitly describe which framework you are using.
> 
> It also should be derived class of `AbstractLogger<T>`.


How about Trace and Debug levels?

2023-07-14 18:16 UTC, Tymisko requested changes

2023-07-14 18:16 UTC, Tymisko commented on src/main/java/org/weathertrack/util/logger/LogbackLogger.java
> +	public LogbackLogger(Class<T> className) {
`className` is not a valid paramter name. `Class<T>` is not a string.

2023-07-14 19:26 UTC, Tymisko approved these changes

2023-07-14 19:33 UTC, Tymisko requested changes

2023-07-14 19:33 UTC, Tymisko commented on .idea/sonarlint/issuestore/0/b/0b94eed6ac949458337e2826f9ae5d20679c8636
Please add `**/.idea/sonarlint/` to `.gitignore`

2023-07-14 19:38 UTC, Tymisko approved these changes

2023-07-14 19:38 UTC, merged