Issue/#6 implement weather data provider integration
FreakyF/Weather-track pull request #34
Opened 2023-07-27 17:03 UTC by FreakyF

Closes #6

2023-07-27 18:14 UTC, Tymisko requested changes

2023-07-27 18:14 UTC, Tymisko commented on src/main/java/org/weathertrack/weather/provider/openmeteo/model/weather/WeatherInterpretationResource.java
> +	public static String interpretWeatherCode(int code) {
You get the code. Just convert it to string and invoke `properties.getProperty(code)` and return the value.
This way even if you change the properties file it should return the actual one - imagine if the user changes his language at runtime.

2023-07-27 18:14 UTC, Tymisko commented on src/main/java/org/weathertrack/weather/provider/openmeteo/model/weather/WeatherInterpretationResource.java
> +	public static String interpretWeatherCode(int code) {
By this entire weatherDescription is redundant

2023-07-27 18:14 UTC, Tymisko commented on src/test/java/org/weathertrack/input/service/userio/CommandLineUserIOServiceTests.java
> +	void printCityDataWithSameCityName_shouldPrintCityData() {
As before - backward changes to name of the method

2023-07-27 18:14 UTC, Tymisko commented on src/test/java/org/weathertrack/input/service/userio/CommandLineUserIOServiceTests.java
> +	void printCityDataWithSameCityName_singleCity() {
This test name does not follow the pattern `methodName_ShouldX_WhenY` nor `methodName_WhenY_ShouldX`

2023-07-27 18:14 UTC, Tymisko commented on src/test/java/org/weathertrack/input/service/userio/CommandLineUserIOServiceTests.java
> +	void printCityDataWithSameCityName_emptyList() {
This test name does not follow the pattern `methodName_ShouldX_WhenY` nor `methodName_WhenY_ShouldX`

2023-07-27 18:14 UTC, Tymisko commented on src/test/java/org/weathertrack/input/service/userio/CommandLineUserIOServiceTests.java
> +		commandLineUserInterface.printCityDataWithSameCityName(cityData);
This test name does not follow the pattern `methodName_ShouldX_WhenY` nor `methodName_WhenY_ShouldX`

2023-07-27 18:14 UTC, Tymisko commented on src/test/java/org/weathertrack/weather/provider/openmeteo/geocoding/OpenMeteoGeocodingProviderTests.java
> +	// fetchCityDataFromCityName
Remove these redundant tests.
In the future create tests with `throw new UnsupportedOperationException()`

2023-07-27 18:14 UTC, Tymisko commented on src/test/java/org/weathertrack/weather/provider/openmeteo/geocoding/OpenMeteoGeocodingProviderTests.java
> +	// NoData
Remove these redundant tests.
In the future create tests with `throw new UnsupportedOperationException()`

2023-07-28 09:34 UTC, FreakyF commented on src/main/java/org/weathertrack/weather/provider/openmeteo/geocoding/OpenMeteoGeocodingProvider.java
> +	private static final String GEOCODING_API_SCHEME = "https";
I cannot merge it, because it will throw `java.lang.IllegalArgumentException: URI with undefined scheme`.

2023-08-15 17:18 UTC, closed without merging